### ISSUE TITLE
Slight fixes in various components

### ISSUE THREAD

**Issue by ThePhoenix08** [mendacium-a11y/Shortify#10]
Heres what I am proposing to add:
- add database.sqlite in .gitignore to ignore the development mode generated sqlite file
- reduce redundancy by improving routing
- - shifting navbar and footer to routing instead of importing and placing them on each page
- - shifting the gradient background div to gradient background of app.tsx div
- navabar sticky to top
- fix the Button's in navbar to house anchor tags to respective pages for navigation
-  adding asChild to Button components to remove the console errors
- fix dialog description child cant be div console error
- fix trigger cant have button as child console error
- fix mail link in footer

These are set of very minor changes and fixes to improve the overall application slightly. I request the mentor to assign me this issue under KWoC.

**Comment by mendacium-a11y** [comment]
this looks good, why dont you create a pr and i'll review it
