### ISSUE TITLE
Configure ESlint

### ISSUE THREAD

**Issue by mendacium-a11y** [mendacium-a11y/Shortify#14]
#### Tasks:
- #### Backend:
  - Configure ESLint with appropriate plugins and rules for Node.js/Express development.
  - Ensure compatibility with the project's backend framework and dependencies.
  - Use ```.eslintignore ```to exclude files/directories such as node_modules, build artifacts, or other unneeded files from linting.

- #### Frontend:
  - Configure ESLint with plugins and rules tailored for React (or the specific frontend framework in use).
  - Ensure compatibility with JSX, modern JavaScript, and styling standards.
  - Use ```.eslintignore ``` to exclude files/directories such as node_modules, build artifacts, or generated files from linting.

- #### Additional Notes:
  - Use separate ```.eslintrc.cjs``` files for each environment (backend/ and frontend/).
  - Define shared rules in a root ESLint configuration, if applicable.
  -  Document the ```.eslintignore``` structure and explain why certain files are excluded.

- #### Deliverables:
  - Properly configured ESLint setup for both backend and frontend.
  -```  .eslintignore ```files added and configured for both environments.
  - Documentation on how to run ESLint for each environment, including how ignored files are handled.

**Comment by Archi-shaw** [comment]
@mendacium-a11y  Please assign this issue to mee.

**Comment by mendacium-a11y** [comment]
@Archi-shaw done, if you face any problem, we have a discord server too, you can ask for help there

**Comment by Archi-shaw** [comment]
@mendacium-a11y  Completed
