### ISSUE TITLE
Fix redirect page

### ISSUE THREAD

**Issue by mendacium-a11y** [mendacium-a11y/Shortify#2]
## Description

When redirects are triggered, a plain white page is displayed momentarily. This affects the user experience by making the transition feel slow and unpolished. The primary logic for handling the redirect seems to take time to execute.

##Expected Behavior

The redirection process should be faster and visually appealing, ensuring a smoother user experience. Ideally:
- Reduce the time taken for the redirect logic to execute.
- Replace the white page with a simple, styled loading indicator or transition effect to enhance the aesthetic.

**Comment by SGI-CAPP-AT2** [comment]
Hey I can fix this, I want to know value of `VITE_API_URL` env variable.

**Comment by mendacium-a11y** [comment]
its localhost:3000, thanks for pointing that out, i'll open an issue for an example env too

**Comment by SGI-CAPP-AT2** [comment]
What we're doing currently is handling redirects on client side which is not a good practice 
Instead we should have a get endpoint for `/r/` at server side for that we must know which url should user have

I want to know at production what is `VITE_API_URL` are you changing it or it is handled automatically by onrender[dot]com

**Comment by mendacium-a11y** [comment]
not the best idea to use prod for development, you can set up the backend locally, its very straightforward and not resource intensive either

**Comment by SGI-CAPP-AT2** [comment]
No I dont want to use production url but If i use `http://VIT_API_URL/r/:id`
to user for shortened link will it work in production or not
