### ISSUE TITLE
Email not provided in the footer

### ISSUE THREAD

**Issue by abhirajadhikary06** [mendacium-a11y/Shortify#4]
@mendacium-a11y would like to solve this small issue for not and join you again during the KWOC. 
Hope you would assign the issue .

**Comment by mendacium-a11y** [comment]
could you expand on the issue a bit more?

**Comment by abhirajadhikary06** [comment]
![image](https://github.com/user-attachments/assets/b0546475-2df1-4432-984d-4add378289d7)
**The Email in the footer section has no associated email. If the details were provided to me I would like to add the email to it.**
Maybe this contribution would not be counted for KWOC, so I would like to further work for this project when KWOC coding period starts.

**Comment by mendacium-a11y** [comment]
![image](https://github.com/user-attachments/assets/831fe952-ba08-495a-a6dd-ec47ca7a9b75)

there is an email associated with the link
